name: "CI"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

jobs:
    check:
        name: "Check"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "stable"
            - uses: "Swatinem/rust-cache@v2"
            - uses: "actions-rs/cargo@v1"
              with:
                  command: "check"

    test:
        name: "Test Suite"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "stable"
                  components: "llvm-tools-preview"
            - name: "Retreive cached dependecies"
              uses: "Swatinem/rust-cache@v2"
            - name: "Setup coverage env"
              uses: "taiki-e/install-action@cargo-llvm-cov"
            - name: "Generate code coverage"
              run: "cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info"
            - name: "Upload coverage reports to Codecov"
              uses: "codecov/codecov-action@v3"
              with:
                  files: "lcov.info"
                  fail_ci_if_error: false

    fmt:
        name: "Rustfmt"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "stable"
            - run: "rustup component add rustfmt"
            - uses: "actions-rs/cargo@v1"
              with:
                  command: "fmt"
                  args: "--all -- --check"

    clippy:
        name: "Clippy"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "Setup cmake"
              uses: "jwlawson/actions-setup-cmake@v1.13"
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "nightly"
            - run: "rustup component add clippy"
            - uses: "actions-rs/cargo@v1"
              with:
                  command: "clippy"
                  args: "-- -D warnings"
